services:
    _defaults:
        autoconfigure: true
        autowire: true

    _instanceof:
        Sg\DatatablesBundle\Datatable\Column\Column:
            tags: ['sg_datatables.column']

    Sg\DatatablesBundle\Datatable\Column\:
        resource: '../../Datatable/Column/*'

    Sg\DatatablesBundle\Datatable\AbstractDatatable:
        abstract: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@translator'
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@twig'
            - ! tagged sg_datatables.column

    Sg\DatatablesBundle\Response\DatatableResponse:
        public: true
        arguments:
            - '@request_stack'

    Sg\DatatablesBundle\Datatable\DatatableFactory:
        public: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@translator'
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@twig'

    Sg\DatatablesBundle\Twig\DatatableTwigExtension: ~

    # aliases for backwards compatibility, will be removed in 2.0
    sg_datatables.twig.extension:
        alias: Sg\DatatablesBundle\Twig\DatatableTwigExtension

    sg_datatables.datatable.abstract:
        alias: Sg\DatatablesBundle\Datatable\AbstractDatatable

    sg_datatables.response:
        alias: Sg\DatatablesBundle\Response\DatatableResponse
        public: true

    sg_datatables.factory:
        alias: Sg\DatatablesBundle\Datatable\DatatableFactory
        public: true
