services:
    sg_datatables.serializer.method:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
    sg_datatables.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
    sg_datatables.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - [@sg_datatables.serializer.method]
            - [@sg_datatables.serializer.encoder.json]
    sg_datatables.twig.extension:
        class: Sg\DatatablesBundle\Twig\DatatableTwigExtension
        arguments: [@translator, %sg_datatables.routes%]
        tags:
            - { name: twig.extension }
    sg_datatables.query:
        class: Sg\DatatablesBundle\Datatable\Data\DatatableDataManager
        arguments: [@request_stack, @sg_datatables.serializer, %sg_datatables.query%]
    sg_datatables.routing.loader:
        class: Sg\DatatablesBundle\Routing\DatatablesRoutingLoader
        arguments: [%sg_datatables.routes%, %sg_datatables.fields%, %sg_datatables.roles%]
        tags:
            - { name: routing.loader }
    sg_datatables.view.container:
        class: Sg\DatatablesBundle\Datatable\View\DatatableViewContainer
